### ISSUE TITLE
[epic] MVP in go

### ISSUE THREAD

**Issue by rufuspollock** [datopian/datahub-cli#1]
Minimal go based `datahub-cli`

## Command Line

The command line is our MVP. It is also the primary tool for our primary audience of power data wranglers. The command line is power, speed, and simplicity (for those familiar with it).

Key actions

```bash=
## push

# stdin - to your scratchpad data package
cat xyz.csv | datahub push

# stdin to data package
cat xyz.csv | datahub push my-data-package

# explicit path (less important!)
datahub push xyz.csv


# get/pull
# by default simply outputs to stdin
datahub get {publisher}/{dataset}/{name}[.extension]

# (can also download to current directory (or even to stdin)
datahub get {publisher}/{dataset}/{name}[.extension] {dir or path}
```

Comments:

* You don't even need a data package (or know data packages to get started)
  * => server has to do job of generating this for you / updating datapackage.json as you add new files ...
* would love to be able to get started with no config info at all (other than username?)
  * => `sandbox` publisher anyone can publish to (if no username)
  * publisher (user) but no data package => publish to `scratchpad` data package within your publisher

Config wanted:

```
username
token
server
```

## Acceptance Criteria

* [ ] `push` implemented as per above
* [ ] `get` implemented as per above
* [ ] frictionless install experience (e.g.. a simple download of a binary)

### Prep and Planning

* [x] Define minimal `datahub-cli`
* [x] Evaluate python vs go option
  * [x] SCQA
  * [x] Research heroku approach
* [ ] Plan out MVP
  * [ ] Play around with go
    * [ ] Get started with go - [notes][go-started]
    * [ ] Research heroku approach further
    * [ ] Decide whether we want to work top down porting heroku-cli or bottom up from a clean app we make ourselves
      * That requires playing around
  * [ ] Choose key libraries
    * [ ] Command line library - cobra
    * [ ] Config parsing library - viper
    * [ ] Testing library - ginkgo etc
  * [ ] Work out how we can compile for different platforms - http://stackoverflow.com/questions/12168873/cross-compile-go-on-osx
  * [ ] Develop plan

**Comment by rufuspollock** [comment]
## CLI plan and Heroku Analysis

*These are my notes written up whilst doing the heroku analysis*

* go is base and wraps individual node commands - it is the execution system and marshaller (bring together all the list of plugins)
* node system
  * cli utilities
  * api wrapper (?)

Questions:

* What do heroku Plugin objects look like and how do they differ from cobra ones?
* How does heroku use go to execute node code?
  * Plugin.runFn and  This creates a lightweight wrapper node script and then runs it with the local node executable `Plugin.runScript`
* How does not code call the API (and have access  to auth)
* Do we code push command in nodejs plugin or in go?
  * go
    * pros: (?) try out go ...
    * cons: duplicate node work, have to learn go ...
  * nodejs
    * pros: datapackage-js library already there ... - core focus (think electron apps ...)
    * cons: need to build the go-node bridge. Something we need to sometime (if we do ultimately allow node plugins)
	* My sense is that nodejs is probably needed at some point and so let's go with it now. (so why split - why not be entirely consistent ??)

## Research Heroku

```mermaid
graph TD

  main --> start[start.Start]
  subgraph start.go
    start --> loadNewCLI[update.loadNewCLI - does nothing if autoupdate=False]
    loadNewCLI --> findcmd["cmd = AllCommands().Find(Args[1]) - defaults to dashboard commandd if Args[1] empty"]
    findcmd --> cmd.Run[cmd.Run - search for command based on first arg and then run]
  end

  subgraph command.go
    findcmd --> allcmds
    allcmds["AllCommands()"]
  end

  subgraph plugin.go
    allcmds --> UserPlugins
    allcmds --> CorePlugins
    UserPlugins
    CorePlugins
    cmd.Run --"Plugins.Commands()"--> pa[command.Plugin.runFunc]
  end

  subgraph node.go
    pa --p.RunScript--> nodex[Plugin.RunScript]
  end
```

* command.go: this is the basic definition of a command
  * CLITopics = List of Topics. Each Topic has a list of commands.
* loadNewCli: this actually executes the cli bin file from within the go code: $DATAHOME/cli/bin/heroku (sort of weird as we are already in the code code)
  * `filesystem.go`: `DATAHOME = /.local/share/heroku/cli`

```mermaid
graph LR

  start[start.go - kick-off point in code]
  update[update.go - auto updating code]
  command[command.go - Command struct]
  help[help.go - helpInvalidCommand]
  topic[topic.go - Topic struct = list of commands, Topic.Commands]
```

**Plugins - plugins.go**

This is important as it is the way we link into the node plugins.

```go=
// CorePlugins are built in plugins
var CorePlugins = &Plugins{Path: filepath.Join(AppDir, "lib")}                           

// UserPlugins are user-installable plugins
var UserPlugins = &Plugins{Path: filepath.Join(DataHome, "plugins")}

Plugins struct = array of Plugins

// Commands lists all the commands of the plugins
func (p *Plugins) Commands() (commands Commands) {
  for _, plugin := range p.Plugins() {
    for _, command := range plugin.Commands {
      command.Run = p.runFn(plugin, command.Topic, command.Command)
      commands = append(commands, command) }                         
  }
  return                               
}

func (p *Plugins) runFn(plugin *Plugin, topic, command string) func(ctx *Context) {
  return func(ctx *Context) {
    p.readLockPlugin(plugin.Name)
    ctx.Dev = p.isPluginSymlinked(plugin.Name)
    ctxJSON, err := json.Marshal(ctx)
    must(err)
    args, err := json.Marshal(Args)
    must(err)

    script := fmt.Sprintf(`'use strict'
process.argv = %s
let pluginName = '%s'
let pluginVersion = '%s'
let topic = '%s'
let command = '%s'
let ctx = %s
ctx.version = ctx.version + ' ' + pluginName + '/' + pluginVersion + ' node-' + process.version
if (command === '') { command = null }
let plugin = require(pluginName)
let cmd = plugin.commands.filter((c) => c.topic === topic && c.command == command)[0]

function handleEPIPE (err) {
  if (err.errno !== 'EPIPE') throw err
}
process.stdout.on('error', handleEPIPE)
process.stderr.on('error', handleEPIPE)
if (!ctx.dev) process.on('unhandledRejection', () => { })

cmd.run(ctx)
`, args, plugin.Name, plugin.Version, topic, command, ctxJSON)

    // swallow sigint since the plugin will handle it
    swallowSigint = true

    if ctx.Dev {
      currentAnalyticsCommand = nil
    } else {
      currentAnalyticsCommand.Plugin = plugin.Name
      currentAnalyticsCommand.PluginVersion = plugin.Version
      currentAnalyticsCommand.Language = "node"
    }

    cmd, done := p.RunScript(script)
    cmd.Stdin = os.Stdin
    cmd.Stdout = os.Stdout
    cmd.Stderr = os.Stderr
    err = cmd.Run()
    done()
    Exit(getExitCode(err))
  }
}

// ParsePlugin requires the plugin's node module
// to get the commands and metadata
func (p *Plugins) ParsePlugin(name, tag string) (*Plugin, error) {
  script := `
  var plugin = require('` + name + `')
  var pjson  = require('` + name + `/package.json')

  plugin.name    = pjson.name
  plugin.version = pjson.version

  console.log(JSON.stringify(plugin))`
  cmd, done := p.RunScript(script)
  cmd.Stderr = Stderr
  output, err := cmd.Output()
  done()
  ....
```

```mermaid
graph TD

  a[Plugins.Commands - for each Command on a plugin & defines Command.Run as plugin.runFunc]
  b[runFunc - generate a wrapper javascript to call the node js then ...]
  c[Plugin.RunScript - runs the previous script]

  a --> b
  b --> c

```
