### ISSUE TITLE
version command

### ISSUE THREAD

**Issue by rufuspollock** [datopian/datahub-cli#2]
Version command to print out current version.

## Acceptance Criteria

* [x] Prints versions and exits

## Tasks

* [x] `version` command
* [x] test for this

Extras

* [ ] version includes git tag and timestamp https://www.atatus.com/blog/golang-auto-build-versioning/

**Comment by rufuspollock** [comment]
FIXED.
