### ISSUE TITLE
Research heroku approach to its CLI

### ISSUE THREAD

**Issue by rufuspollock** [datopian/datahub-cli#3]
Research how the heroku CLI works, in particular its combination of a go base with nodejs based plugins -- with most of the core functionality in the plugins.

https://github.com/heroku/cli
https://devcenter.heroku.com/articles/developing-cli-plugins

## Acceptance criteria

* [ ] Description of the heroku cli structure esp how go code uses the node plugins
  * [ ] What CLI library it uses (if any) and how we could migrate this to cobra (if that is what we are using)
* [ ] Decision on whether to reuse parts of this and if so how

## Tasks

* [x] Dig through the code
* [x] Document main code execution path
* [x] Understand nodejs plugins model

----

## Results

Notes

* What do i like about them?
  * heroku cli is a joy to use and elegant (e.g. colouring etc)
  * Do cross-platform builds already
  * Built something in ruby and refactored to go (and probably thought about it)
  * have a plugins system
  * go + node plugins seems smart (solid core plus extensibility in lang everyone knows)
* They don't use a command line library afaict but roll their own
  * [x] TODO - Research command line libraries.
* They have pretty minimal testing https://circleci.com/gh/heroku/cli/1916

      cli_suite_test.go
      command_test.go
      debug_test.go
      flag_test.go
      help_test.go
      main_test.go
      update_test.go
      version_test.go

**Comment by rufuspollock** [comment]
FIXED. This research is basically done.

> Decision on whether to reuse parts of this and if so how

Lots to reuse from heroku approach (with some tweaking): the go - node intregration is nicely done (and working!) and it looks reasonably straightforward to convert over to cobra and our setup

>  Description of the heroku cli structure esp how go code uses the node plugins
> * What CLI library it uses (if any) and how we could migrate this to cobra (if that is what we are using)

Description above is updated with my detailed analysis of the heroku CLI structure and how this could work.
